// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmployee = "Employee"

// Employee mapped from table <Employee>
type Employee struct {
	ID             int64     `gorm:"column:Id;primaryKey" json:"Id"`                   // 雇员Id
	OrgID          int64     `gorm:"column:Org_Id" json:"Org_Id"`                      // Id
	EmpNo          string    `gorm:"column:Emp_No" json:"Emp_No"`                      // 雇员编号
	EmpName        string    `gorm:"column:Emp_Name" json:"Emp_Name"`                  // 雇员名称
	EmpMobile      string    `gorm:"column:Emp_Mobile" json:"Emp_Mobile"`              // 雇员手机号
	InsertDateTime time.Time `gorm:"column:Insert_Date_Time" json:"Insert_Date_Time"`  // 插入时间
	InsertUser     int64     `gorm:"column:Insert_User" json:"Insert_User"`            // 插入用户
	UpdateDateTime time.Time `gorm:"column:Update_Date_Time" json:"Update_Date_Time"`  // 更新时间
	UpdateUser     int64     `gorm:"column:Update_User" json:"Update_User"`            // 更新用户
	Version        int32     `gorm:"column:Version;default:1" json:"Version"`          // 版本
	Deleted        string    `gorm:"column:Deleted;not null;default:0" json:"Deleted"` // 删除标志(0:正常 1 删除)
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
