// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLogisticsCompany = "Logistics_Company"

// LogisticsCompany mapped from table <Logistics_Company>
type LogisticsCompany struct {
	ID               int64     `gorm:"column:Id;primaryKey" json:"Id"`                      // 物流公司Id
	CompanyName      string    `gorm:"column:Company_Name" json:"Company_Name"`             // 公司名称/车企名称
	Corporation      string    `gorm:"column:Corporation" json:"Corporation"`               // 法人姓名
	Type             int32     `gorm:"column:Type" json:"Type"`                             // 类型(0:个人 1 :公司 2 车队)
	Tel              string    `gorm:"column:Tel" json:"Tel"`                               // 手机号
	BankNo           string    `gorm:"column:Bank_no" json:"Bank_no"`                       // 银行卡
	PlateTotalIncome float64   `gorm:"column:Plate_Total_Income" json:"Plate_Total_Income"` // 平台总收益
	AccountQuota     float64   `gorm:"column:Account_Quota" json:"Account_Quota"`           // 账户限额
	RegisterDate     time.Time `gorm:"column:Register_Date" json:"Register_Date"`           // 注册时间
	Sign             int32     `gorm:"column:Sign;default:1" json:"Sign"`                   // 是否签约(0:未签约 1 已签约)
}

// TableName LogisticsCompany's table name
func (*LogisticsCompany) TableName() string {
	return TableNameLogisticsCompany
}
