// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrdersGood = "Orders_Goods"

// OrdersGood mapped from table <Orders_Goods>
type OrdersGood struct {
	ID        int64  `gorm:"column:Id;primaryKey" json:"Id"`      // 货物Id
	OrdID     int64  `gorm:"column:Ord_id" json:"Ord_id"`         // 订单Id
	GoodsName string `gorm:"column:goods_name" json:"goods_name"` // 货物名称
	Weight    string `gorm:"column:weight" json:"weight"`         // 重量
	Volume    string `gorm:"column:volume" json:"volume"`         // 体积
	Size      string `gorm:"column:size" json:"size"`             // 尺寸
}

// TableName OrdersGood's table name
func (*OrdersGood) TableName() string {
	return TableNameOrdersGood
}
