// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrdersFinance = "Orders_Finances"

// OrdersFinance mapped from table <Orders_Finances>
type OrdersFinance struct {
	ID           int64     `gorm:"column:Id;primaryKey" json:"Id"`              // 结算Id
	OrdID        int64     `gorm:"column:Ord_id" json:"Ord_id"`                 // 订单Id
	Type         int32     `gorm:"column:type" json:"type"`                     // 结算类型(0 收款 1 付款)
	NonTaxAmount float64   `gorm:"column:non_tax_amount" json:"non_tax_amount"` // 不含税金额
	TaxRate      float64   `gorm:"column:tax_rate" json:"tax_rate"`             // 税率
	Total        float64   `gorm:"column:total" json:"total"`                   // 价税合计
	BillTag      int32     `gorm:"column:bill_tag" json:"bill_tag"`             // 是否开票
	OperateDate  time.Time `gorm:"column:operate_date" json:"operate_date"`     // 收款/付款时间
	OperateWay   int32     `gorm:"column:operate_way" json:"operate_way"`       // 收款/付款方式(0 线下 2 银行卡 3 微信支付 4 支付宝)
}

// TableName OrdersFinance's table name
func (*OrdersFinance) TableName() string {
	return TableNameOrdersFinance
}
