// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrdersFee = "Orders_Fee"

// OrdersFee mapped from table <Orders_Fee>
type OrdersFee struct {
	ID             int64   `gorm:"column:Id;primaryKey" json:"Id"`                  // 订单费用Id
	OrdID          int64   `gorm:"column:Ord_id" json:"Ord_id"`                     // 订单Id
	PickUpFee      float64 `gorm:"column:pick_up_fee" json:"pick_up_fee"`           // 提货费
	DeliveryFee    float64 `gorm:"column:delivery_fee" json:"delivery_fee"`         // 送货费
	TransportFee   float64 `gorm:"column:transport_fee" json:"transport_fee"`       // 干线费
	UnloadingFee   float64 `gorm:"column:unloading_fee" json:"unloading_fee"`       // 卸载费
	QuoteFee       float64 `gorm:"column:quote_fee" json:"quote_fee"`               // 报价金额
	PremiumFee     float64 `gorm:"column:premium_fee" json:"premium_fee"`           // 保费
	NonTaxFee      float64 `gorm:"column:non_tax_fee" json:"non_tax_fee"`           // 不含税金额
	TaxRate        float64 `gorm:"column:tax_rate" json:"tax_rate"`                 // 税率
	BondedFeeTotal float64 `gorm:"column:bonded_fee_total" json:"bonded_fee_total"` // 保税合计
}

// TableName OrdersFee's table name
func (*OrdersFee) TableName() string {
	return TableNameOrdersFee
}
