// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysResource = "Sys_Resources"

// SysResource mapped from table <Sys_Resources>
type SysResource struct {
	Id10                   int64     `gorm:"column:Id10;primaryKey" json:"Id10"`                              // 资源Id
	SysId10                int64     `gorm:"column:Sys_Id10" json:"Sys_Id10"`                                 // 资源Id
	ResourceIdentity       string    `gorm:"column:Resource_Identity;not null" json:"Resource_Identity"`      // 资源标示
	ResourceType           int32     `gorm:"column:Resource_Type;not null" json:"Resource_Type"`              // 资源类型(0 app   1 模块  2  菜单 3  页面 4  按钮 5  扩展按钮)
	ResourceStatus         int32     `gorm:"column:Resource_Status" json:"Resource_Status"`                   // 资源状态(0:正常 1 :停用)
	ResourceActopnType     int32     `gorm:"column:Resource_Actopn_Type" json:"Resource_Actopn_Type"`         // 资源动作类型 (-1 无 1.增加;2 删 3 改 4 上传 5导出 6 查询 .)
	ResourceActionIdentity string    `gorm:"column:Resource_Action_Identity" json:"Resource_Action_Identity"` // 资源动作标示(针对扩展按钮，备用字段)
	ResourceDesc           string    `gorm:"column:Resource_Desc" json:"Resource_Desc"`                       // 资源描述
	ResourceOrders         int32     `gorm:"column:Resource_Orders" json:"Resource_Orders"`                   // 资源序序号
	InsertDateTime4        time.Time `gorm:"column:Insert_Date_Time4;not null" json:"Insert_Date_Time4"`      // 插入时间
	InsertUser3            int64     `gorm:"column:Insert_User3;not null" json:"Insert_User3"`                // 插入用户
	UpdateDateTime3        time.Time `gorm:"column:Update_Date_Time3" json:"Update_Date_Time3"`               // 更新时间
	UpdateUser3            int64     `gorm:"column:Update_User3" json:"Update_User3"`                         // 更新用户
	Version4               int32     `gorm:"column:Version4;not null" json:"Version4"`                        // 版本
	Deleted3               string    `gorm:"column:Deleted3;not null" json:"Deleted3"`                        // 删除标志
	CompayId3              int64     `gorm:"column:Compay_Id3;not null" json:"Compay_Id3"`                    // 公司
}

// TableName SysResource's table name
func (*SysResource) TableName() string {
	return TableNameSysResource
}
