// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserRole = "Sys_User_Roles"

// SysUserRole mapped from table <Sys_User_Roles>
type SysUserRole struct {
	Id14 int64 `gorm:"column:Id14;primaryKey" json:"Id14"`
	Id3  int64 `gorm:"column:Id3" json:"Id3"` // 角色Id
	Id2  int64 `gorm:"column:Id2" json:"Id2"` // Id
}

// TableName SysUserRole's table name
func (*SysUserRole) TableName() string {
	return TableNameSysUserRole
}
