// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUserGroup = "Sys_User_Group"

// SysUserGroup mapped from table <Sys_User_Group>
type SysUserGroup struct {
	ID             int64     `gorm:"column:Id;primaryKey" json:"Id"`                           // Id
	SysID          int64     `gorm:"column:Sys_Id" json:"Sys_Id"`                              // Id
	SysId2         int64     `gorm:"column:Sys_Id2" json:"Sys_Id2"`                            // Id
	UserGroupType  int32     `gorm:"column:User_Group_Type" json:"User_Group_Type"`            // 用户组类型
	UserGroupDesc  string    `gorm:"column:User_Group_Desc" json:"User_Group_Desc"`            // 用户组描述
	InsertDateTime time.Time `gorm:"column:Insert_Date_Time;not null" json:"Insert_Date_Time"` // 插入时间
	InsertUser     int64     `gorm:"column:Insert_User;not null" json:"Insert_User"`           // 插入用户
	UpdateDateTime time.Time `gorm:"column:Update_Date_Time" json:"Update_Date_Time"`          // 更新时间
	UpdateUser     int64     `gorm:"column:Update_User" json:"Update_User"`                    // 更新用户
	Version        int32     `gorm:"column:Version;not null" json:"Version"`                   // 版本
	Deleted        string    `gorm:"column:Deleted;not null" json:"Deleted"`                   // 删除标志(0:正常 1 删除)
	CompayID       int64     `gorm:"column:Compay_Id;not null" json:"Compay_Id"`               // 公司
}

// TableName SysUserGroup's table name
func (*SysUserGroup) TableName() string {
	return TableNameSysUserGroup
}
