// Code generated by "zld-jy/da/field". DO NOT EDIT.
// Code generated by "zld-jy/da/field". DO NOT EDIT.
// Code generated by "zld-jy/da/field". DO NOT EDIT.

package model

const TableNameSysRolePermissionGroup = "Sys_Role_Permission_Group"

// SysRolePermissionGroup mapped from table <Sys_Role_Permission_Group>
type SysRolePermissionGroup struct {
	Id7 int64 `gorm:"column:Id7;primaryKey" json:"Id7"`
	Id6 int64 `gorm:"column:Id6" json:"Id6"` // Id
	Id3 int64 `gorm:"column:Id3" json:"Id3"` // 角色Id
}

// TableName SysRolePermissionGroup's table name
func (*SysRolePermissionGroup) TableName() string {
	return TableNameSysRolePermissionGroup
}
