// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysPermissionGroup = "Sys_Permission_Group"

// SysPermissionGroup mapped from table <Sys_Permission_Group>
type SysPermissionGroup struct {
	Id6                 int64     `gorm:"column:Id6;primaryKey" json:"Id6"`                           // Id
	SysId6              int64     `gorm:"column:Sys_Id6" json:"Sys_Id6"`                              // Id
	PermissionGroupType int32     `gorm:"column:Permission_Group_Type" json:"Permission_Group_Type"`  // 许可组类型
	PermissionGroupDesc string    `gorm:"column:Permission_Group_Desc" json:"Permission_Group_Desc"`  // 许可组描述
	InsertDateTime2     time.Time `gorm:"column:Insert_Date_Time2;not null" json:"Insert_Date_Time2"` // 插入时间
	InsertUser4         int64     `gorm:"column:Insert_User4;not null" json:"Insert_User4"`           // 插入用户
	UpdateDateTime2     time.Time `gorm:"column:Update_Date_Time2" json:"Update_Date_Time2"`          // 更新时间
	UpdateUser4         int64     `gorm:"column:Update_User4" json:"Update_User4"`                    // 更新用户
	Version2            int32     `gorm:"column:Version2;not null" json:"Version2"`                   // 版本
	Deleted4            string    `gorm:"column:Deleted4;not null" json:"Deleted4"`                   // 删除标志(0:正常 1 删除)
	CompayId2           int64     `gorm:"column:Compay_Id2;not null" json:"Compay_Id2"`               // 公司
}

// TableName SysPermissionGroup's table name
func (*SysPermissionGroup) TableName() string {
	return TableNameSysPermissionGroup
}
