// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysRole = "Sys_Roles"

// SysRole mapped from table <Sys_Roles>
type SysRole struct {
	Id3             int64     `gorm:"column:Id3;primaryKey" json:"Id3"`                           // 角色Id
	RoleCode        string    `gorm:"column:Role_Code;not null" json:"Role_Code"`                 // 角色代码
	RoleName        string    `gorm:"column:Role_Name;not null" json:"Role_Name"`                 // 角色名称
	InsertDateTime3 time.Time `gorm:"column:Insert_Date_Time3;not null" json:"Insert_Date_Time3"` // 插入时间
	InsertUser2     int64     `gorm:"column:Insert_User2;not null" json:"Insert_User2"`           // 插入用户
	UpdateDateTime4 time.Time `gorm:"column:Update_Date_Time4" json:"Update_Date_Time4"`          // 更新时间
	UpdateUser2     int64     `gorm:"column:Update_User2" json:"Update_User2"`                    // 更新用户
	Version3        int32     `gorm:"column:Version3;not null" json:"Version3"`                   // 版本
	Deleted2        string    `gorm:"column:Deleted2;not null" json:"Deleted2"`                   // 删除标志(0:正常 1 删除)
	CompayID        int64     `gorm:"column:Compay_Id;not null" json:"Compay_Id"`                 // 公司
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
