// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUserGroup = "Sys_User_Group"

// SysUserGroup mapped from table <Sys_User_Group>
type SysUserGroup struct {
	Id8             int64     `gorm:"column:Id8;primaryKey" json:"Id8"`                           // Id
	SysId8          int64     `gorm:"column:Sys_Id8" json:"Sys_Id8"`                              // Id
	Id2             int64     `gorm:"column:Id2" json:"Id2"`                                      // Id
	UserGroupType   int32     `gorm:"column:User_Group_Type" json:"User_Group_Type"`              // 用户组类型
	UserGroupDesc   string    `gorm:"column:User_Group_Desc" json:"User_Group_Desc"`              // 用户组描述
	InsertDateTime2 time.Time `gorm:"column:Insert_Date_Time2;not null" json:"Insert_Date_Time2"` // 插入时间
	InsertUser4     int64     `gorm:"column:Insert_User4;not null" json:"Insert_User4"`           // 插入用户
	UpdateDateTime2 time.Time `gorm:"column:Update_Date_Time2" json:"Update_Date_Time2"`          // 更新时间
	UpdateUser4     int64     `gorm:"column:Update_User4" json:"Update_User4"`                    // 更新用户
	Version2        int32     `gorm:"column:Version2;not null" json:"Version2"`                   // 版本
	Deleted4        string    `gorm:"column:Deleted4;not null" json:"Deleted4"`                   // 删除标志(0:正常 1 删除)
	CompayId2       int64     `gorm:"column:Compay_Id2;not null" json:"Compay_Id2"`               // 公司
}

// TableName SysUserGroup's table name
func (*SysUserGroup) TableName() string {
	return TableNameSysUserGroup
}
