// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUser = "Sys_Users"

// SysUser mapped from table <Sys_Users>
type SysUser struct {
	ID             int64     `gorm:"column:Id;primaryKey" json:"Id"`                  // Id
	SysID          int64     `gorm:"column:Sys_Id" json:"Sys_Id"`                     // Id
	EmpID          int64     `gorm:"column:Emp_Id" json:"Emp_Id"`                     // 雇员Id
	UserName       string    `gorm:"column:User_Name" json:"User_Name"`               // 用户名称
	UserEmail      string    `gorm:"column:User_Email" json:"User_Email"`             // 用户邮箱
	UserPassword   string    `gorm:"column:User_Password" json:"User_Password"`       // 登录密码
	UserStatus     int32     `gorm:"column:User_Status" json:"User_Status"`           // 用户状态(0:正常 1 :停用 )
	UserType       int32     `gorm:"column:User_Type" json:"User_Type"`               // 用户类型
	InsertDateTime time.Time `gorm:"column:Insert_Date_Time" json:"Insert_Date_Time"` // 插入时间
	InsertUser     int64     `gorm:"column:Insert_User" json:"Insert_User"`           // 插入用户
	UpdateDateTime time.Time `gorm:"column:Update_Date_Time" json:"Update_Date_Time"` // 更新时间
	UpdateUser     int64     `gorm:"column:Update_User" json:"Update_User"`           // 更新用户
	Version        int32     `gorm:"column:Version" json:"Version"`                   // 版本
	Deleted        string    `gorm:"column:Deleted;not null" json:"Deleted"`          // 删除标志(0:正常 1 删除)
	CompayID       int64     `gorm:"column:Compay_Id" json:"Compay_Id"`               // 公司
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
