// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysPermissionItem = "Sys_Permission_Item"

// SysPermissionItem mapped from table <Sys_Permission_Item>
type SysPermissionItem struct {
	Id11              int64  `gorm:"column:Id11;primaryKey" json:"Id11"`                    // Id
	Id6               int64  `gorm:"column:Id6" json:"Id6"`                                 // Id
	Id10              int64  `gorm:"column:Id10" json:"Id10"`                               // 资源Id
	PermissionItemVal int32  `gorm:"column:Permission_Item_Val" json:"Permission_Item_Val"` // 权限值
	PermissionType    int32  `gorm:"column:Permission_Type" json:"Permission_Type"`         // 权限类型
	PermissionDesc    string `gorm:"column:Permission_Desc" json:"Permission_Desc"`         // 权限描述
}

// TableName SysPermissionItem's table name
func (*SysPermissionItem) TableName() string {
	return TableNameSysPermissionItem
}
