// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysRole = "Sys_Roles"

// SysRole mapped from table <Sys_Roles>
type SysRole struct {
	ID             int64     `gorm:"column:Id;primaryKey" json:"Id"`                           // 角色Id
	RoleCode       string    `gorm:"column:Role_Code;not null" json:"Role_Code"`               // 角色代码
	RoleName       string    `gorm:"column:Role_Name;not null" json:"Role_Name"`               // 角色名称
	InsertDateTime time.Time `gorm:"column:Insert_Date_Time;not null" json:"Insert_Date_Time"` // 插入时间
	InsertUser     int64     `gorm:"column:Insert_User;not null" json:"Insert_User"`           // 插入用户
	UpdateDateTime time.Time `gorm:"column:Update_Date_Time" json:"Update_Date_Time"`          // 更新时间
	UpdateUser     int64     `gorm:"column:Update_User" json:"Update_User"`                    // 更新用户
	Version        int32     `gorm:"column:Version;not null" json:"Version"`                   // 版本
	Deleted        string    `gorm:"column:Deleted;not null" json:"Deleted"`                   // 删除标志(0:正常 1 删除)
	CompayID       int64     `gorm:"column:Compay_Id;not null" json:"Compay_Id"`               // 公司
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
