// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysPermission = "Sys_Permission"

// SysPermission mapped from table <Sys_Permission>
type SysPermission struct {
	Id6                         int64  `gorm:"column:Id6;primaryKey" json:"Id6"`                                            // Id
	PermissionVal               int32  `gorm:"column:Permission_Val" json:"Permission_Val"`                                 // 权限值
	PermissionDesc2             string `gorm:"column:Permission_Desc2" json:"Permission_Desc2"`                             // 权限描述
	AppPermissionVal            int32  `gorm:"column:App_Permission_Val" json:"App_Permission_Val"`                         // 平台权限值
	ModulePermissionVal         int32  `gorm:"column:Module_Permission_Val" json:"Module_Permission_Val"`                   // 模块权限值
	MenuPermissionVal           int32  `gorm:"column:Menu_Permission_Val" json:"Menu_Permission_Val"`                       // 菜单权限值
	PagePermissionVal           int32  `gorm:"column:Page_Permission_Val" json:"Page_Permission_Val"`                       // 页面权限值
	CommonOperatorPermissionVal int32  `gorm:"column:Common_Operator_Permission_Val" json:"Common_Operator_Permission_Val"` // 通用操作权限值
	PermissionScope             string `gorm:"column:Permission_Scope" json:"Permission_Scope"`                             // 权限空间
}

// TableName SysPermission's table name
func (*SysPermission) TableName() string {
	return TableNameSysPermission
}
