// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysOpenUser = "Sys_Open_Users"

// SysOpenUser mapped from table <Sys_Open_Users>
type SysOpenUser struct {
	ID           int64  `gorm:"column:Id;primaryKey" json:"Id"`            // Id
	OpenIdentity string `gorm:"column:Open_Identity" json:"Open_Identity"` // 平台标示
	OpenName     string `gorm:"column:Open_Name" json:"Open_Name"`         // 平台名称
	OpenType     int32  `gorm:"column:Open_Type" json:"Open_Type"`         // 开发平台类型(1:钉钉 2: 微信 )
	OpenMemo1    string `gorm:"column:Open_Memo1" json:"Open_Memo1"`       // 平台扩展
}

// TableName SysOpenUser's table name
func (*SysOpenUser) TableName() string {
	return TableNameSysOpenUser
}
