// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"zld-jy/da/model"
)

func newSysRolePermissionGroup(db *gorm.DB) sysRolePermissionGroup {
	_sysRolePermissionGroup := sysRolePermissionGroup{}

	_sysRolePermissionGroup.sysRolePermissionGroupDo.UseDB(db)
	_sysRolePermissionGroup.sysRolePermissionGroupDo.UseModel(&model.SysRolePermissionGroup{})

	tableName := _sysRolePermissionGroup.sysRolePermissionGroupDo.TableName()
	_sysRolePermissionGroup.ALL = field.NewAsterisk(tableName)
	_sysRolePermissionGroup.Id7 = field.NewInt64(tableName, "Id7")
	_sysRolePermissionGroup.Id6 = field.NewInt64(tableName, "Id6")
	_sysRolePermissionGroup.Id3 = field.NewInt64(tableName, "Id3")

	_sysRolePermissionGroup.fillFieldMap()

	return _sysRolePermissionGroup
}

type sysRolePermissionGroup struct {
	sysRolePermissionGroupDo sysRolePermissionGroupDo

	ALL field.Asterisk
	Id7 field.Int64
	Id6 field.Int64 // Id
	Id3 field.Int64 // 角色Id

	fieldMap map[string]field.Expr
}

func (s sysRolePermissionGroup) Table(newTableName string) *sysRolePermissionGroup {
	s.sysRolePermissionGroupDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRolePermissionGroup) As(alias string) *sysRolePermissionGroup {
	s.sysRolePermissionGroupDo.DO = *(s.sysRolePermissionGroupDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRolePermissionGroup) updateTableName(table string) *sysRolePermissionGroup {
	s.ALL = field.NewAsterisk(table)
	s.Id7 = field.NewInt64(table, "Id7")
	s.Id6 = field.NewInt64(table, "Id6")
	s.Id3 = field.NewInt64(table, "Id3")

	s.fillFieldMap()

	return s
}

func (s *sysRolePermissionGroup) WithContext(ctx context.Context) *sysRolePermissionGroupDo {
	return s.sysRolePermissionGroupDo.WithContext(ctx)
}

func (s sysRolePermissionGroup) TableName() string { return s.sysRolePermissionGroupDo.TableName() }

func (s sysRolePermissionGroup) Alias() string { return s.sysRolePermissionGroupDo.Alias() }

func (s *sysRolePermissionGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRolePermissionGroup) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 3)
	s.fieldMap["Id7"] = s.Id7
	s.fieldMap["Id6"] = s.Id6
	s.fieldMap["Id3"] = s.Id3
}

func (s sysRolePermissionGroup) clone(db *gorm.DB) sysRolePermissionGroup {
	s.sysRolePermissionGroupDo.ReplaceDB(db)
	return s
}

type sysRolePermissionGroupDo struct{ gen.DO }

func (s sysRolePermissionGroupDo) Debug() *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRolePermissionGroupDo) WithContext(ctx context.Context) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRolePermissionGroupDo) ReadDB() *sysRolePermissionGroupDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRolePermissionGroupDo) WriteDB() *sysRolePermissionGroupDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRolePermissionGroupDo) Clauses(conds ...clause.Expression) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRolePermissionGroupDo) Returning(value interface{}, columns ...string) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRolePermissionGroupDo) Not(conds ...gen.Condition) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRolePermissionGroupDo) Or(conds ...gen.Condition) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRolePermissionGroupDo) Select(conds ...field.Expr) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRolePermissionGroupDo) Where(conds ...gen.Condition) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRolePermissionGroupDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *sysRolePermissionGroupDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s sysRolePermissionGroupDo) Order(conds ...field.Expr) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRolePermissionGroupDo) Distinct(cols ...field.Expr) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRolePermissionGroupDo) Omit(cols ...field.Expr) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRolePermissionGroupDo) Join(table schema.Tabler, on ...field.Expr) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRolePermissionGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRolePermissionGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRolePermissionGroupDo) Group(cols ...field.Expr) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRolePermissionGroupDo) Having(conds ...gen.Condition) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRolePermissionGroupDo) Limit(limit int) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRolePermissionGroupDo) Offset(offset int) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRolePermissionGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRolePermissionGroupDo) Unscoped() *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRolePermissionGroupDo) Create(values ...*model.SysRolePermissionGroup) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRolePermissionGroupDo) CreateInBatches(values []*model.SysRolePermissionGroup, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRolePermissionGroupDo) Save(values ...*model.SysRolePermissionGroup) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRolePermissionGroupDo) First() (*model.SysRolePermissionGroup, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermissionGroup), nil
	}
}

func (s sysRolePermissionGroupDo) Take() (*model.SysRolePermissionGroup, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermissionGroup), nil
	}
}

func (s sysRolePermissionGroupDo) Last() (*model.SysRolePermissionGroup, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermissionGroup), nil
	}
}

func (s sysRolePermissionGroupDo) Find() ([]*model.SysRolePermissionGroup, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysRolePermissionGroup), err
}

func (s sysRolePermissionGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRolePermissionGroup, err error) {
	buf := make([]*model.SysRolePermissionGroup, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRolePermissionGroupDo) FindInBatches(result *[]*model.SysRolePermissionGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRolePermissionGroupDo) Attrs(attrs ...field.AssignExpr) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRolePermissionGroupDo) Assign(attrs ...field.AssignExpr) *sysRolePermissionGroupDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRolePermissionGroupDo) Joins(fields ...field.RelationField) *sysRolePermissionGroupDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRolePermissionGroupDo) Preload(fields ...field.RelationField) *sysRolePermissionGroupDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRolePermissionGroupDo) FirstOrInit() (*model.SysRolePermissionGroup, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermissionGroup), nil
	}
}

func (s sysRolePermissionGroupDo) FirstOrCreate() (*model.SysRolePermissionGroup, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermissionGroup), nil
	}
}

func (s sysRolePermissionGroupDo) FindByPage(offset int, limit int) (result []*model.SysRolePermissionGroup, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRolePermissionGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRolePermissionGroupDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRolePermissionGroupDo) Delete(models ...*model.SysRolePermissionGroup) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRolePermissionGroupDo) withDO(do gen.Dao) *sysRolePermissionGroupDo {
	s.DO = *do.(*gen.DO)
	return s
}
