// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameArea = "Areas"

// Area mapped from table <Areas>
type Area struct {
	ID            int64  `gorm:"column:id;primaryKey" json:"id"`                // 区域Id
	Code          string `gorm:"column:code" json:"code"`                       // 区域code
	Name          string `gorm:"column:name" json:"name"`                       // 区域名称
	CityCode      string `gorm:"column:city_code" json:"city_code"`             // 城市Code
	Sort          int32  `gorm:"column:sort" json:"sort"`                       // 排序索引
	ShortName     string `gorm:"column:short_name" json:"short_name"`           // 简称
	Status        int32  `gorm:"column:status" json:"status"`                   // 状态(0:启用 1 停用)
	ShowShortName string `gorm:"column:show_short_name" json:"show_short_name"` // 显示简称名称
	Custom        int32  `gorm:"column:custom" json:"custom"`                   // 是否自定义(0:否 1 是)
}

// TableName Area's table name
func (*Area) TableName() string {
	return TableNameArea
}
