// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameBillingOrder = "Billing_Orders"

// BillingOrder mapped from table <Billing_Orders>
type BillingOrder struct {
	ID                    int64     `gorm:"column:Id;primaryKey" json:"Id"`                                // 开票Id
	CusID                 int64     `gorm:"column:Cus_Id" json:"Cus_Id"`                                   // 客户Id
	CompanyName           string    `gorm:"column:company_name" json:"company_name"`                       // 公司名称
	ApplyNo               string    `gorm:"column:apply_no" json:"apply_no"`                               // 发票申请单号
	ApplyAmount           float64   `gorm:"column:apply_amount" json:"apply_amount"`                       // 申请金额
	ApplyDate             time.Time `gorm:"column:apply_date" json:"apply_date"`                           // 申请时间
	Status                int32     `gorm:"column:status" json:"status"`                                   // 票据状态(0 待申请 1 开票中 2 已开票 3 已驳回 4作废)
	BillingNo             string    `gorm:"column:billing_no" json:"billing_no"`                           // 发票编号
	TaxpayerIDNumber      string    `gorm:"column:taxpayer_ID_number" json:"taxpayer_ID_number"`           // 纳税人识别号
	Tel                   string    `gorm:"column:tel" json:"tel"`                                         // 电话
	Address               string    `gorm:"column:address" json:"address"`                                 // 地址
	BankName              string    `gorm:"column:bank_name" json:"bank_name"`                             // 开户银行
	BankAccount           string    `gorm:"column:bank_account" json:"bank_account"`                       // 开户账户
	ConsigneePerson       string    `gorm:"column:consignee_person" json:"consignee_person"`               // 收货人
	ConsigneeProvinceCode string    `gorm:"column:consignee_province_code" json:"consignee_province_code"` // 收货省份Code
	ConsigneeCityCode     string    `gorm:"column:consignee_city_code" json:"consignee_city_code"`         // 收货城市Code
	ConsigneeAreaCode     string    `gorm:"column:consignee_area_code" json:"consignee_area_code"`         // 收货地区code
	ConsigneeAddress      string    `gorm:"column:consignee_address" json:"consignee_address"`             // 收货详细地址
	ConsigneeEmail        string    `gorm:"column:consignee_email" json:"consignee_email"`                 // 收货人邮箱
	ConsigneeTel          string    `gorm:"column:consignee_tel" json:"consignee_tel"`                     // 收货人电话
	BillingDate           time.Time `gorm:"column:billing_date" json:"billing_date"`                       // 开票时间
}

// TableName BillingOrder's table name
func (*BillingOrder) TableName() string {
	return TableNameBillingOrder
}
