// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameBillsOrdersItem = "Bills_Orders_Item"

// BillsOrdersItem mapped from table <Bills_Orders_Item>
type BillsOrdersItem struct {
	ID    int64 `gorm:"column:Id;primaryKey" json:"Id"` // 开票申请单明细Id
	OrdID int64 `gorm:"column:Ord_id" json:"Ord_id"`    // 订单Id
	BilID int64 `gorm:"column:Bil_Id" json:"Bil_Id"`    // 开票Id
}

// TableName BillsOrdersItem's table name
func (*BillsOrdersItem) TableName() string {
	return TableNameBillsOrdersItem
}
