// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameCustomer = "Customers"

// Customer mapped from table <Customers>
type Customer struct {
	ID              int64     `gorm:"column:Id;primaryKey" json:"Id"`                           // 客户Id
	CustomerName    string    `gorm:"column:Customer_Name;not null" json:"Customer_Name"`       // 客户名称
	CustomerAddress string    `gorm:"column:Customer_Address" json:"Customer_Address"`          // 客户地址
	ContactMan      string    `gorm:"column:Contact_Man" json:"Contact_Man"`                    // 客户联系人
	ContactTel      string    `gorm:"column:Contact_Tel" json:"Contact_Tel"`                    // 客户电话
	EnterTel        string    `gorm:"column:Enter_Tel" json:"Enter_Tel"`                        // 企业联系人
	ProvinceCode    string    `gorm:"column:Province_Code" json:"Province_Code"`                // 省code
	CityCode        string    `gorm:"column:City_Code" json:"City_Code"`                        // 市code
	AreaCode        string    `gorm:"column:Area_Code" json:"Area_Code"`                        // 区code
	Memo            string    `gorm:"column:Memo" json:"Memo"`                                  // 备注
	InsertDateTime  time.Time `gorm:"column:Insert_Date_Time;not null" json:"Insert_Date_Time"` // 插入时间
	InsertUser      int64     `gorm:"column:Insert_User;not null" json:"Insert_User"`           // 插入用户
	UpdateDateTime  time.Time `gorm:"column:Update_Date_Time" json:"Update_Date_Time"`          // 更新时间
	UpdateUser      int64     `gorm:"column:Update_User" json:"Update_User"`                    // 更新用户
	Version         int32     `gorm:"column:Version;not null" json:"Version"`                   // 版本
	Deleted         string    `gorm:"column:Deleted;not null" json:"Deleted"`                   // 删除标志(0:正常 1 删除)
	CompayID        int64     `gorm:"column:Compay_Id;not null" json:"Compay_Id"`               // 公司
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
