// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameCustomerPoject = "Customer_Pojects"

// CustomerPoject mapped from table <Customer_Pojects>
type CustomerPoject struct {
	ID          int64  `gorm:"column:Id;primaryKey" json:"Id"`          // 项目Id
	CusID       int64  `gorm:"column:Cus_Id" json:"Cus_Id"`             // 客户Id
	ProjectName string `gorm:"column:Project_Name" json:"Project_Name"` // 项目名称
	ProjectDesc string `gorm:"column:Project_Desc" json:"Project_Desc"` // 项目描述
	ProjectMemo string `gorm:"column:Project_Memo" json:"Project_Memo"` // 说明
}

// TableName CustomerPoject's table name
func (*CustomerPoject) TableName() string {
	return TableNameCustomerPoject
}
