// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameIDGENERATOR = "ID_GENERATOR"

// IDGENERATOR mapped from table <ID_GENERATOR>
type IDGENERATOR struct {
	ID           int64  `gorm:"column:id;primaryKey" json:"id"`                     // id生成器id
	FlagNo       string `gorm:"column:flag_no;not null" json:"flag_no"`             // 标示符
	BeginValue   int64  `gorm:"column:begin_value;not null" json:"begin_value"`     // 开始值
	CurrentValue int64  `gorm:"column:current_value;not null" json:"current_value"` // 目前值
	EndValue     int64  `gorm:"column:end_value;not null" json:"end_value"`         // 结束值
	Memo         string `gorm:"column:memo;not null" json:"memo"`                   // 备注
	CompanyID    int64  `gorm:"column:company_id" json:"company_id"`                // 分公司Id
}

// TableName IDGENERATOR's table name
func (*IDGENERATOR) TableName() string {
	return TableNameIDGENERATOR
}
