// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameOrder = "Orders"

// Order mapped from table <Orders>
type Order struct {
	ID                   int64     `gorm:"column:id;primaryKey" json:"id"`                              // 订单Id
	LogID                int64     `gorm:"column:Log_Id" json:"Log_Id"`                                 // 物流公司Id
	OrderNo              string    `gorm:"column:order_no;not null" json:"order_no"`                    // 订单号
	OutOrderNo           string    `gorm:"column:out_order_no" json:"out_order_no"`                     // 外部订单号
	ProjectName          string    `gorm:"column:project_name" json:"project_name"`                     // 项目名称
	ShipmentDate         time.Time `gorm:"column:shipment_date" json:"shipment_date"`                   // 托运时间
	Status               int32     `gorm:"column:status" json:"status"`                                 // 订单状态(0:草稿 1:已下单 2:已接单 3: 已装货 4: 已签收)
	DeliverProvinceCode  string    `gorm:"column:deliver_province_code" json:"deliver_province_code"`   // 发货省code
	DeliverCityCode      string    `gorm:"column:deliver_city_code" json:"deliver_city_code"`           // 发货城市Code
	DeliverAreaCode      string    `gorm:"column:deliver_area_code" json:"deliver_area_code"`           // 发货地区Code
	DeliverAddress       string    `gorm:"column:deliver_address" json:"deliver_address"`               // 出发地
	ArriveProvinceCode   string    `gorm:"column:arrive_province_code" json:"arrive_province_code"`     // 到达省份Code
	ArriveCityCode       string    `gorm:"column:arrive_city_code" json:"arrive_city_code"`             // 到达城市Code
	ArriveAreaCode       string    `gorm:"column:arrive_area_code" json:"arrive_area_code"`             // 到达地区Code
	ArriveAddress        string    `gorm:"column:arrive_address" json:"arrive_address"`                 // 到达地
	ArriveDate           time.Time `gorm:"column:arrive_date" json:"arrive_date"`                       // 到达时间
	ReceiptCustomer      string    `gorm:"column:receipt_customer" json:"receipt_customer"`             // 收货客户
	ReceiptCustomerTel   string    `gorm:"column:receipt_customer_tel" json:"receipt_customer_tel"`     // 收货客户电话
	PricingMethod        int32     `gorm:"column:pricing_method" json:"pricing_method"`                 // 计价方式(0: 趟 1 吨 2 方)
	ReturnBillAttachment string    `gorm:"column:return_bill_attachment" json:"return_bill_attachment"` // 回单附件
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
