// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameOrderStatus = "Order_Status"

// OrderStatus mapped from table <Order_Status>
type OrderStatus struct {
	ID          int64  `gorm:"column:Id;primaryKey" json:"Id"`                   // 订单费用Id
	OrdID       int64  `gorm:"column:Ord_id" json:"Ord_id"`                      // 订单Id
	OrderStatus int32  `gorm:"column:Order_Status;not null" json:"Order_Status"` // 订单状态(0:草稿 1:已下单 2:已接单 3: 已装货 4: 已签收)
	OrderDesc   string `gorm:"column:Order_Desc;not null" json:"Order_Desc"`     // 描述
	Memo        string `gorm:"column:Memo" json:"Memo"`                          // 备注
}

// TableName OrderStatus's table name
func (*OrderStatus) TableName() string {
	return TableNameOrderStatus
}
