// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameSysUserGroupRole = "sys_User_Group_Roles"

// SysUserGroupRole mapped from table <sys_User_Group_Roles>
type SysUserGroupRole struct {
	ID     int64 `gorm:"column:Id;primaryKey" json:"Id"`
	SysID  int64 `gorm:"column:Sys_Id" json:"Sys_Id"`   // 角色Id
	SysId2 int64 `gorm:"column:Sys_Id2" json:"Sys_Id2"` // Id
}

// TableName SysUserGroupRole's table name
func (*SysUserGroupRole) TableName() string {
	return TableNameSysUserGroupRole
}
