// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameSysReourceExt = "Sys_Reource_Ext"

// SysReourceExt mapped from table <Sys_Reource_Ext>
type SysReourceExt struct {
	ID             int64  `gorm:"column:Id" json:"Id"`                           // 资源Id
	Component      string `gorm:"column:Component" json:"Component"`             // 组件
	AlwaysShow     bool   `gorm:"column:Always_Show" json:"Always_Show"`         // 显示
	MetaTitle      string `gorm:"column:Meta_Title" json:"Meta_Title"`           // 标题
	MetaLimit      string `gorm:"column:Meta_Limit" json:"Meta_Limit"`           // 元数据限制
	MetaBreadcrumb string `gorm:"column:Meta_Breadcrumb" json:"Meta_Breadcrumb"` // 元数据面包屑
	MetaIcon       string `gorm:"column:Meta_Icon" json:"Meta_Icon"`             // 元数据图标
	MetaNoCache    string `gorm:"column:Meta_No_Cache" json:"Meta_No_Cache"`     // 元数据缓存
	MetaHidden     string `gorm:"column:Meta_Hidden" json:"Meta_Hidden"`         // 元数据隐藏域
	Redirect       string `gorm:"column:Redirect" json:"Redirect"`               // 重定向URL
	Hidden         string `gorm:"column:Hidden" json:"Hidden"`                   // 隐藏域
	Type           int32  `gorm:"column:Type" json:"Type"`                       // 类型
}

// TableName SysReourceExt's table name
func (*SysReourceExt) TableName() string {
	return TableNameSysReourceExt
}
