// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameSysPermissionGroup = "Sys_Permission_Group"

// SysPermissionGroup mapped from table <Sys_Permission_Group>
type SysPermissionGroup struct {
	ID                  int64     `gorm:"column:Id;primaryKey" json:"Id"`                            // Id
	SysID               int64     `gorm:"column:Sys_Id" json:"Sys_Id"`                               // Id
	PermissionGroupType int32     `gorm:"column:Permission_Group_Type" json:"Permission_Group_Type"` // 许可组类型
	PermissionGroupDesc string    `gorm:"column:Permission_Group_Desc" json:"Permission_Group_Desc"` // 许可组描述
	InsertDateTime      time.Time `gorm:"column:Insert_Date_Time;not null" json:"Insert_Date_Time"`  // 插入时间
	InsertUser          int64     `gorm:"column:Insert_User;not null" json:"Insert_User"`            // 插入用户
	UpdateDateTime      time.Time `gorm:"column:Update_Date_Time" json:"Update_Date_Time"`           // 更新时间
	UpdateUser          int64     `gorm:"column:Update_User" json:"Update_User"`                     // 更新用户
	Version             int32     `gorm:"column:Version;not null" json:"Version"`                    // 版本
	Deleted             string    `gorm:"column:Deleted;not null" json:"Deleted"`                    // 删除标志(0:正常 1 删除)
	CompayID            int64     `gorm:"column:Compay_Id;not null" json:"Compay_Id"`                // 公司
}

// TableName SysPermissionGroup's table name
func (*SysPermissionGroup) TableName() string {
	return TableNameSysPermissionGroup
}
