// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameVehicle = "Vehicles"

// Vehicle mapped from table <Vehicles>
type Vehicle struct {
	ID           int64  `gorm:"column:Id;primaryKey" json:"Id"`            // 车辆Id
	LogID        int64  `gorm:"column:Log_Id" json:"Log_Id"`               // 物流公司Id
	LicensePlate string `gorm:"column:License_Plate" json:"License_Plate"` // 车牌
	Model        string `gorm:"column:Model" json:"Model"`                 // 车型(厢式/平板/高栏/爬梯)
	Len          string `gorm:"column:Len" json:"Len"`                     // 车长(4.2/6.8/9.6/13/13.75/17.5)
	Memo         string `gorm:"column:Memo" json:"Memo"`                   // 备注
}

// TableName Vehicle's table name
func (*Vehicle) TableName() string {
	return TableNameVehicle
}
