// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auths/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "登录接口",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginUsers"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/customers/dao": {
            "get": {
                "description": "查询客户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "查询客户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "currentIndex",
                        "in": "dao"
                    },
                    {
                        "type": "string",
                        "name": "customerName",
                        "in": "dao"
                    },
                    {
                        "type": "integer",
                        "example": 10,
                        "name": "pageSize",
                        "in": "dao"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users/getUsers": {
            "get": {
                "description": "根据用户ID获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "default": "1",
                        "description": "登录参数",
                        "name": "userId",
                        "in": "dao",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UsersInfo"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "注册用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "description": "注册用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Result"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.LoginUsers": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "wxllx@124343.com"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "zhangsan"
                }
            }
        },
        "models.RegisterUser": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "zxl222@asas"
                },
                "tel": {
                    "description": "手机号",
                    "type": "string",
                    "example": "18011329010"
                },
                "userEmail": {
                    "description": "用户邮箱",
                    "type": "string",
                    "example": "zhangsan@163.com"
                },
                "username": {
                    "description": "用户名称",
                    "type": "string",
                    "example": "zhangsan"
                }
            }
        },
        "models.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "models.UsersInfo": {
            "type": "object",
            "properties": {
                "empName": {
                    "description": "雇员名称",
                    "type": "string"
                },
                "empNo": {
                    "description": "雇员编号",
                    "type": "string"
                },
                "userEmail": {
                    "description": "用户邮箱",
                    "type": "string"
                },
                "userId": {
                    "description": "用户Id",
                    "type": "integer"
                },
                "userName": {
                    "description": "用户名称",
                    "type": "string"
                },
                "userType": {
                    "description": "用户类型",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
